e2e:
  environment: dev
  protocol:
    unionEndpoint: https://${e2e.environment}-api.rarible.org
    indexerEndpoint: https://${e2e.environment}-${e2e.blockchain}-dev.rarible.org
  contentStorage:
    endpoint: http://nexus.rarible.int/repository/e2e
  blockchains:
    - ethereum
